FROM yobasystems/alpine:3.8-aarch64
LABEL maintainer "Dominic Taylor <dominic@yobasystems.co.uk>" architecture="ARM64v8/aarch64" version="8.11.3" alpineversion="3.8.1" build="28-nov-2018"

RUN apk add --no-cache nodejs nodejs-npm
