FROM yobasystems/alpine:3.8-amd64
LABEL maintainer "Dominic Taylor <dominic@yobasystems.co.uk>" architecture="AMD64/x86_64" version="8.11.3" alpineversion="3.8.1" build="28-nov-2018"

RUN apk add --no-cache nodejs nodejs-npm
